# param:     1000 M
# flops:     3.93 M
# clean acc: 93.8%

## ---- Component search_space ----
# ---- Type cnn ----
search_space_type: cnn
search_space_cfg:
  # Schedulable attributes: 
  cell_layout: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]
  num_cell_groups: 3
  num_init_nodes: 1
  num_layers: 62
  num_node_inputs: 1
  num_steps: 1
  reduce_cell_groups:
  - 1
  shared_primitives: # this is not used
  - none
 
# ---- End Type cnn ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: cifar10
dataset_cfg:
  # Schedulable attributes: 
  cutout: null
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component final_model ----
# ---- Type cnn_genotype ----
final_model_type: cnn_final_model
final_model_cfg:
  # Schedulable attributes: dropout_path_rate
  genotypes: "normal_0=[('dense_block', 0, 1)], reduce_1=[('dense_reduce_block', 0, 1)], normal_2=[('bn_relu', 0, 1)]"
  auxiliary_cfg: null
  auxiliary_head: false
  layer_channels: [48, 72, 96, 120, 144, 168, 192, 96, 120, 144, 168, 192, 216, 240, 264, 288, 312, 336, 360, 384, 192, 216, 240, 264, 288, 312, 336, 360, 384, 408, 432, 456, 480, 504, 528, 552, 576, 600, 624, 648, 672, 696, 720, 744, 768, 384, 408, 432, 456, 480, 504, 528, 552, 576, 600, 624, 648, 672, 696, 720, 744, 768, 768]
  dropout_path_rate: 0.0
  dropout_rate: 0.0
  init_channels: 48
  num_classes: 10
  cell_use_preprocess: false
  schedule_cfg: null
  stem_multiplier: 1
  use_stem: conv_3x3
  stem_stride: 1
  stem_affine: true
# ---- End Type cnn_genotype ----
## ---- End Component final_model ----

objective_type: classification

## ---- Component final_trainer ----
# ---- Type cnn_trainer ----
final_trainer_type: cnn_trainer
final_trainer_cfg:
  # Schedulable attributes: 
  auxiliary_head: false
  auxiliary_weight: 0.0
  add_regularization: true
  batch_size: 128
  epochs: 100
  grad_clip: 5.0
  learning_rate: 0.05
  momentum: 0.9
  no_bias_decay: false
  optimizer_scheduler:
    eta_min: 0.001
    T_max: 100
    type: CosineAnnealingLR
  schedule_cfg: null
  warmup_epochs: 0
  weight_decay: 0.0003
  save_as_state_dict: true
  eval_no_grad: false
# ---- End Type cnn_trainer ----
## ---- End Component final_trainer ----
