# param: 2.3 M
# flops: 182 M
# clean acc: 0.925


## ---- Component search_space ----
# ---- Type cnn ----
search_space_type: cnn
search_space_cfg:
  # Schedulable attributes:
  cell_layout:  [0, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3]
  # cell_layout:  [0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3]
  num_cell_groups: 4
  num_init_nodes: 1
  num_layers: 18
  num_node_inputs: 1
  num_steps: 1
  reduce_cell_groups:
  - 2
  shared_primitives: # this is not used
  - none
# ---- End Type cnn ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: cifar10
dataset_cfg:
  # Schedulable attributes: 
  cutout: null
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component final_model ----
# ---- Type cnn_genotype ----
final_model_type: cnn_final_model
final_model_cfg:
  # Schedulable attributes: dropout_path_rate
  genotypes: "normal_0=[('mobilenet_block_1', 0, 1)], normal_1=[('mobilenet_block_6', 0, 1)], reduce_2=[('mobilenet_block_6', 0, 1)], normal_3=[('conv_bn_relu_1x1', 0, 1)]"
  auxiliary_cfg: null
  auxiliary_head: false
  layer_channels: [32, 16, 24, 24, 32, 32, 32, 64, 64, 64, 64, 96, 96, 96, 160, 160, 160, 320, 1280]
  dropout_path_rate: 0.0
  dropout_rate: 0.0
  init_channels: 32
  num_classes: 10
  cell_use_preprocess: false
  schedule_cfg: null
  stem_multiplier: 1
  use_stem: conv_bn_relu_3x3
  stem_stride: 1
  stem_affine: true
# ---- End Type cnn_genotype ----
## ---- End Component final_model ----

objective_type: classification
objective_cfg: {}

## ---- Component final_trainer ----
# ---- Type cnn_trainer ----
final_trainer_type: cnn_trainer
final_trainer_cfg:
  # Schedulable attributes: 
  auxiliary_head: false
  auxiliary_weight: 0.0
  add_regularization: true
  batch_size: 128
  epochs: 100
  grad_clip: 5.0
  learning_rate: 0.1
  momentum: 0.9
  no_bias_decay: false
  optimizer_type: SGD
  optimizer_scheduler:
    type: MultiStepLR
    milestones: [40, 80]
    gamma: 0.1
  schedule_cfg: null
  warmup_epochs: 0
  weight_decay: 0.00004
  save_as_state_dict: true
# ---- End Type cnn_trainer ----
## ---- End Component final_trainer ----
