rollout_type: mnasnet_ofa
# param: 2.3 M
# flops: 182 M
# clean acc: 0.925


## ---- Component search_space ----
# ---- Type mnasnet_ofa ----
search_space_type: mnasnet_ofa
search_space_cfg:
  num_cell_groups: 6
  num_channels: [6, 6, 6, 6, 6, 6]
  schedule_cfg:
    width_choice:
      type: value
      boundary: [1, 30, 60]
      value: [[6], [6,5], [6,5,4]]
    depth_choice:
      type: value
      boundary: [1, 90, 120]
      value: [[6], [6,5], [6,5,4]]
# ---- End Type mnsanet_ofa ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: cifar10
dataset_cfg:
  # Schedulable attributes: 
  cutout: null
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component controller ----
# ---- Type rl ----
controller_type: ofa
controller_cfg:
  # Schedulable attributes:
  rollout_type: mnasnet_ofa
  force_uniform: true
# ---- End Type rl ----
## ---- End Component controller ----

## ---- Component evaluator ----
# ---- Type mepa ----
evaluator_type: mepa
evaluator_cfg:
  # Schedulable attributes: controller_surrogate_steps, mepa_surrogate_steps, mepa_samples
  load_optimizer: false
  load_scheduler: false
  rollout_type: mnasnet_ofa
  batch_size: 64
  controller_surrogate_steps: 0
  # derive_surrogate_steps: 0
  mepa_surrogate_steps: 0
  mepa_optimizer:
    lr: 0.05
    momentum: 0.9
    type: SGD
    weight_decay: 0.0001
  mepa_scheduler:
    eta_min: 0.0
    T_max: 100
    type: CosineAnnealingLR
  surrogate_optimizer: null
  surrogate_scheduler: null
  mepa_samples: 1
  data_portion:
  - 0.0
  - 0.8 # train evaluator weights
  - 0.2 # for train controller
  mepa_as_surrogate: false
  bptt_steps: 35
  schedule_cfg: null
# ---- End Type mepa ----
## ---- End Component evaluator ----

## ---- Component weights_manager ----
# ---- Type supernet ----
weights_manager_type: mnasnet_supernet
weights_manager_cfg:
  # Schedulable attributes: 
  rollout_type: mnasnet_ofa
# ---- End Type supernet ----
## ---- End Component weights_manager ----

objective_type: ofa_classification
objective_cfg:
  # Schedulable attributes:
  schedule_cfg:
    soft_loss_coeff:
      type: value
      boundary: [1, 30]
      value: [0.0, 1.0]
  soft_loss_coeff: 0.0

## ---- Component trainer ----
# ---- Type simple ----
trainer_type: simple
trainer_cfg:
  # Schedulable attributes: controller_samples, derive_samples
  rollout_type: mnasnet_ofa
  epochs: 100
  test_every: 10
  controller_scheduler: null
  controller_samples: 1
  derive_samples: 8
  evaluator_steps: null
  controller_steps: 0
  controller_train_every: 1
  controller_train_begin: 1001
  interleave_controller_every: null
  schedule_cfg: null
# ---- End Type simple ----
## ---- End Component trainer ----
