## ---- Component search_space ----
# ---- Type cnn ----
search_space_type: cnn
search_space_cfg:
  # Schedulable attributes: 
  cell_layout: [0,0,1,0,1,0,1,0]
  num_cell_groups: 2
  num_init_nodes: 1
  num_layers: 8
  num_node_inputs: 1
  num_steps: 2
  reduce_cell_groups:
  - 1
  shared_primitives:
  - none
  - max_pool_3x3
  - avg_pool_3x3
  - skip_connect
  - sep_conv_3x3
  - dil_conv_3x3
  - relu_conv_bn_3x3
  - conv_1x1
 
# ---- End Type cnn ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: cifar10
dataset_cfg:
  # Schedulable attributes: 
  cutout: 16
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component final_model ----
# ---- Type cnn_genotype ----
final_model_type: cnn_final_model
final_model_cfg:
  # Schedulable attributes: dropout_path_rate
  genotypes: "normal_0=[('relu_conv_bn_3x3', 0, 1), ('relu_conv_bn_3x3', 1, 2), ('skip_connect', 0, 2)], reduce_1=[('relu_conv_bn_3x3', 0, 1), ('relu_conv_bn_3x3', 1, 2), ('conv_1x1', 0, 2)]"
  auxiliary_cfg: null
  auxiliary_head: True
  dropout_path_rate: 0.2
  dropout_rate: 0.1
  init_channels: 64
  num_classes: 10
  schedule_cfg:
    dropout_path_rate:
      type: add
      start: 0
      every: 1
      step: 0.000333 # 0.2/600
  stem_multiplier: 1
  use_stem: True
# ---- End Type cnn_genotype ----
## ---- End Component final_model ----

objective_type: classification

#objective_cfg:
#  fault_loss_coeff: 0.5
#  as_evaluator_regularization: true
#  fault_reward_coeff: 0.5

## ---- Component final_trainer ----
# ---- Type cnn_trainer ----
final_trainer_type: cnn_trainer
final_trainer_cfg:
  # Schedulable attributes: 
  auxiliary_head: true
  auxiliary_weight: 0.4
  add_regularization: true
  batch_size: 128
  epochs: 600
  grad_clip: 5.0
  learning_rate: 0.05
  momentum: 0.9
  no_bias_decay: false
  optimizer_scheduler:
    eta_min: 0.001
    T_max: 600
    type: CosineAnnealingLR
  schedule_cfg: null
  warmup_epochs: 0
  weight_decay: 0.0003
# ---- End Type cnn_trainer ----
## ---- End Component final_trainer ----
