# This file is used to reproduce ENAS results for MLOSS

# The genotype is the top-1 genotype found by enas_search.yaml
# It produces an error rate of 2.89% after final training (2.70% at lowest)
# Batch size has been altered from the original implementation to accommodate our hardware limitation

# The checkpoints and log files are available on OneDrive:
# https://1drv.ms/u/s!AoimKNYWyNYsgeloYQwDj1iSPrYTeA?e=yuo8Vw

## ---- Component search_space ----
# ---- Type cnn ----
search_space_type: cnn
search_space_cfg:
  # Schedulable attributes: 
  cell_layout: null
  num_cell_groups: 2
  num_init_nodes: 2
  num_layers: 20
  num_node_inputs: 2
  num_steps: 5
  reduce_cell_groups:
  - 1
  shared_primitives:
  - max_pool_3x3
  - avg_pool_3x3
  - skip_connect
  - sep_conv_3x3
  - sep_conv_5x5
# ---- End Type cnn ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: cifar10
dataset_cfg:
  # Schedulable attributes: 
  cutout: 16
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component final_model ----
# ---- Type cnn_genotype ----
final_model_type: cnn_final_model
final_model_cfg:
  # Schedulable attributes: dropout_path_rate
  genotypes: CNNGenotype(normal_0=(('sep_conv_5x5', 0, 2), ('skip_connect', 1, 2), ('max_pool_3x3',
    2, 3), ('sep_conv_3x3', 0, 3), ('skip_connect', 2, 4), ('sep_conv_3x3', 2, 4), ('sep_conv_3x3',
    4, 5), ('max_pool_3x3', 1, 5), ('sep_conv_3x3', 3, 6), ('sep_conv_3x3', 5, 6)),
    reduce_1=(('skip_connect', 0, 2), ('sep_conv_5x5', 0, 2), ('skip_connect', 1, 3),
    ('sep_conv_3x3', 0, 3), ('sep_conv_3x3', 1, 4), ('sep_conv_5x5', 0, 4), ('skip_connect',
    3, 5), ('avg_pool_3x3', 4, 5), ('avg_pool_3x3', 2, 6), ('max_pool_3x3', 0, 6)),
    normal_0_concat=(2, 3, 4, 5, 6), reduce_1_concat=(2, 3, 4, 5, 6))
  auxiliary_cfg: null
  auxiliary_head: True
  dropout_path_rate: 0.2
  dropout_rate: 0.1
  init_channels: 36
  num_classes: 10
  schedule_cfg:
    dropout_path_rate:
      type: add
      start: 0
      every: 1
      step: 0.00031 # 0.2/630
  stem_multiplier: 3
# ---- End Type cnn_genotype ----
## ---- End Component final_model ----

## ---- Component final_trainer ----
# ---- Type cnn_trainer ----
final_trainer_type: cnn_trainer
final_trainer_cfg:
  # Schedulable attributes: 
  auxiliary_head: true
  auxiliary_weight: 0.4
  batch_size: 64
  epochs: 630
  grad_clip: 5.0
  learning_rate: 0.025
  momentum: 0.9
  no_bias_decay: false
  optimizer_scheduler:
    eta_min: 0.000001
    T_0: 10
    T_mult: 2
    type: CosineAnnealingWarmRestarts
  schedule_cfg: null
  warmup_epochs: 0
  weight_decay: 0.0002
  save_as_state_dict: true
# ---- End Type cnn_trainer ----
## ---- End Component final_trainer ----

objective_type: classification
objective_cfg:
  {}