## Example CNN NAS configuration
## TODO: generate this config using awnas gen_sample_config

# Search space
search_space_type: cnn
search_space_cfg:
  num_cell_groups: 2
  num_layers: 8

# Dataset
dataset_type: cifar10

# Controller
controller_type: rl
controller_cfg:
  controller_network_type: anchor_lstm
  controller_network_cfg:
    softmax_temperature: 5.0
    # schedule_cfg:
    #   softmax_temperature:
    #     type: mul
    #     start: 5.0
    #     step: 0.1
    #     every: 50
  rl_agent_type: pg
  rl_agent_cfg:
    gamma: 1.0
    entropy_coeff: 0.01
    alpha: 0.99

# Weights manager
weights_manager_type: supernet
weights_manager_cfg:

# Trainer
trainer_type: mepa
trainer_cfg:
  epochs: 200
  batch_size: 64
  data_portion: [0.2, 0.4, 0.4]

  mepa_surrogate_steps: 1
  mepa_samples: 1

  controller_surrogate_steps: 1
  controller_samples: 3
  controller_steps: 313

  mepa_scheduler:
    type: CosineWithRestarts
    t_0: 10
    eta_min: 0.001
    factor: 2.0

  test_every: 5