## ---- Component search_space ----
# ---- Type rnn ----
search_space_type: rnn
search_space_cfg:
  # Schedulable attributes: 
  num_cell_groups: 1
  num_init_nodes: 1
  num_layers: 1
  num_steps: 8
  num_node_inputs: 1
  loose_end: false
  shared_primitives:
  - tanh
  - relu
  - sigmoid
  - identity
# ---- End Type rnn ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type ptb ----
dataset_type: ptb
dataset_cfg:
  # Schedulable attributes: 
  data_dir: ./data/ptb
  shuffle: true
# ---- End Type ptb ----
## ---- End Component dataset ----

## ---- Component controller ----
# ---- Type differentiable ----
controller_type: differentiable
controller_cfg:
  # Schedulable attributes: gumbel_temperature, entropy_coeff
  gumbel_hard: false
  gumbel_temperature: 10.0
  entropy_coeff: 0.0
  max_grad_norm: null
  schedule_cfg:
    gumbel_temperature:
      type: mul
      start: 10.0
      every: 1
      step: 0.926
# ---- End Type differentiable ----
## ---- End Component controller ----

## ---- Component weights_manager ----
# ---- Type rnn_diff_supernet ----
weights_manager_type: rnn_diff_supernet
weights_manager_cfg:
  # Schedulable attributes: 
  num_emb: 300
  num_hid: 300
  tie_weight: true
  decoder_bias: true
  share_primitive_weights: true
  batchnorm_edge: false
  batchnorm_out: true
  max_grad_norm: 0.25
  dropout_emb: 0.0
  dropout_inp0: 0.2
  dropout_inp: 0.75
  dropout_hid: 0.25
  dropout_out: 0.75
  candidate_virtual_parameter_only: false
# ---- End Type rnn_diff_supernet ----
## ---- End Component weights_manager ----

## ---- Component trainer ----
# ---- Type mepa ----
trainer_type: mepa
trainer_cfg:
  # Schedulable attributes: mepa_surrogate_steps, mepa_samples, controller_steps, controller_surrogate_steps, controller_samples
  rollout_type: differentiable
  epochs: 60
  batch_size: 192
  test_every: 5
  surrogate_optimizer: null
  controller_optimizer:
    lr: 3.e-3
    type: Adam
    weight_decay: 1.e-3
  mepa_optimizer:
    lr: 25.
    momentum: 0.
    type: SGD
    weight_decay: 5.e-7
  surrogate_scheduler: null
  controller_scheduler: null
  mepa_scheduler: null
  mepa_surrogate_steps: 0
  mepa_samples: 1
  controller_steps: null
  controller_surrogate_steps: 0
  controller_samples: 1
  controller_train_every: 1
  controller_train_begin: 1
  data_portion:
  - 0.0
  - 0.1
  - 0.9
  derive_queue: controller
  derive_surrogate_steps: 0
  derive_samples: 8
  mepa_as_surrogate: false
  interleave_controller_every: 1
  interleave_report_every: 50
  bptt_steps: 35
  reset_hidden_prob: null
  rnn_reward_c: 80.0
  rnn_act_reg: 0.0
  rnn_slowness_reg: 0.001
  schedule_cfg: null
# ---- End Type mepa ----
## ---- End Component trainer ----

